// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJWZV5oXU4Vx39EAKx00FAOlV8MNkkoKU',
    appId: '1:905111238498:android:853f7d0530ae4a12bfde3b',
    messagingSenderId: '905111238498',
    projectId: 'elang-extension-dev',
    databaseURL: 'https://elang-extension-dev-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'elang-extension-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8IPLPWGcdDiGhr1NsFLBZvyzKoiEA8JY',
    appId: '1:905111238498:ios:502bfef9a4085191bfde3b',
    messagingSenderId: '905111238498',
    projectId: 'elang-extension-dev',
    databaseURL: 'https://elang-extension-dev-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'elang-extension-dev.appspot.com',
    iosClientId: '905111238498-1l4fom9c69i5vlutiuras65vnbgsd1qf.apps.googleusercontent.com',
    iosBundleId: 'com.englishingames.summiShare',
  );
}
